# Generated by Django 3.0.7 on 2020-10-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
        ('Series', '0001_initial'),
        ('Documentales', '0001_initial'),
        ('GoogleDriver', '0002_archivo_en_google_driver_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo_en_google_driver',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anime.Anime'),
        ),
        migrations.AddField(
            model_name='archivo_en_google_driver',
            name='documentales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentales.Documentales'),
        ),
        migrations.AddField(
            model_name='archivo_en_google_driver',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Series.Series'),
        ),
    ]
