# Generated by Django 3.0.7 on 2020-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo_en_mega',
            name='titulo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
