# Generated by Django 3.0.7 on 2020-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActoresModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('facha_nacimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('biografia', models.TextField()),
                ('image', models.ImageField(upload_to='Actores/')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
