# Generated by Django 3.0.7 on 2020-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trailers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='pixel',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
