# Generated by Django 3.0.7 on 2020-10-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuentas', '0001_initial'),
        ('GoogleDriver', '0001_initial'),
        ('Peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo_En_MediLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Imagen De Pelicula/')),
                ('status', models.BooleanField(default=True)),
                ('pixel', models.TextField()),
                ('url_original', models.URLField()),
                ('url_acortada', models.URLField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.Cuenta')),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Peliculas.Peliculas')),
                ('tipo_de_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoogleDriver.Tipo_De_Archivo')),
            ],
        ),
    ]
