# Generated by Django 3.0.7 on 2020-10-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_titulo', models.CharField(max_length=25)),
                ('titulo', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='Banner/')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas.Peliculas')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['titulo'],
            },
        ),
    ]
