# Generated by Django 3.0.7 on 2020-10-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0003_commentpeliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpeliculas',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
    ]
