# Generated by Django 3.0.7 on 2020-10-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0005_auto_20201016_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpeliculas',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
