# Generated by Django 3.0.7 on 2020-10-28 15:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0006_commentpeliculas_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='pixel',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
