# Generated by Django 3.0.7 on 2020-10-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0007_peliculas_pixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='frecha_estreno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='status_subida',
            field=models.CharField(choices=[('Se Estrenara En', 'Se Estrenara En'), ('Proximamante', 'Proximamante'), ('Retrasada', 'Retrasada'), ('Retrasada 30dias', 'Retrasada 30dias'), ('Estreno', 'Estreno'), ('Publicada', 'Publicada'), ('Clausurada', 'Clausurada')], default='Proximamante', max_length=20),
        ),
    ]
