# Generated by Django 3.0.7 on 2020-10-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('temporada', models.CharField(max_length=30)),
                ('capitulos', models.CharField(max_length=30)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Series.Series')),
            ],
        ),
    ]
